---

- name: Boostraping, installing docker python library
  pip:
    name: ['docker']
    state: present

- name: Ensuring {{ docker_certs_path }} exists
  file:
    path: "{{ docker_certs_path }}/{{ item.value.url }}/"
    state: directory
  with_dict: "{{ insecure_docker_registries }}"
  when: item.value.cert

- name: Downloading private certificates
  get_url:
    url: "{{ item.value.cert_file_url }}"
    dest: "{{ docker_certs_path }}/{{ item.value.url }}/ca.crt"
  with_dict: "{{ insecure_docker_registries }}"
  when: item.value.cert

- name: Adding daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    backup: true
  notify: restart docker

- name: Log into private registry
  docker_login:
    registry: "{{ item.value.url }}"
    username: "{{ item.value.user }}"
    password: "{{ item.value.pass }}"
  with_dict: "{{ insecure_docker_registries }}"
  when: item.value.login
