---
- name: Converge
  hosts: all
  vars:
    docker_install_compose: false
    insecure_docker_registries:
      registry_01:
        url: 'nexus.example.com.ar:7443'
        login: false
        user: ''
        pass: ''
        cert: false
        cert_file_url: ''
  roles:
    - role: insecure-registries-docker-role
